on: [push]
name: build
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['9.4.8', '9.6.5', '9.8.2', '9.10.1']
        cabal: ['3.10']
        os: [ubuntu-latest, macOS-latest, windows-latest]
    name: Haskell GHC ${{ matrix.ghc }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal build lib:sequent-calculus exe:sequent-calculus sequent-calculus:unit-tests
      - name: Check examples
        run: ./test_examples.sh
      - run: cabal test
